### ISSUE TITLE
Contact us screen gives an error / warning

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#117]
# Description
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Flexible(flex: 2) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type ParentData.

Usually, this means that the Flexible widget has the wrong ancestor RenderObjectWidget. Typically, Flexible widgets are placed directly inside Flex widgets.
The offending Flexible is currently placed inside a RepaintBoundary widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  Column ← Flexible ← RepaintBoundary ← IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← KeyedSubtree ← SliverList ← MediaQuery ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5761:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5778:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5800:7)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5470:5)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6268:11)
...     Normal element mounting (39 frames)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#45     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1243:37)
#46     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1228:20)
#47     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#48     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1221:12)
#49     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#50     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1962:59)
#51     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:910:15)
#52     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1962:14)
#53     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#54     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:484:5)
#55     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239:19)
#56     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:281:12)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#58     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#59     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#61     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#62     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#63     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#80     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#86     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#87     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
#88     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#89     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#92     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#94     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#99     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#101    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#103    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#104    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#106    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#107    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#112    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3426:14)
#113    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#114    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#115    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#116    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:751:15)
#117    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#118    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#119    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#120    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#121    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#122    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#123    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#124    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#128    _invoke (dart:ui/hooks.dart:150:10)
#129    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#130    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
====================================================================================================
```

# Relevant files
`Contact.dart`

**Comment by rajoriaakash** [comment]
I would like to take this on!
